version: "3.8"

services:
  backend:
    container_name: auto-transactions-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    environment:
      NODE_ENV: production
    restart: always

    volumes:
      - .:/app
      - /app/node_modules

    command: ["npm", "run", "start"]
